# Generated by Django 3.2.5 on 2021-08-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210808_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
