# Generated by Django 3.2.5 on 2021-08-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.URLField(),
        ),
    ]
